{
    "name": "SchoolManagement",
    "version": "15.0.0.0.1",
    "category": "school management",
    "summary": "SchoolManagement for education",
    "author": "BizzAppDev",
    "website": "https://bizzappdev.com",
    "depends": ["base", "mail", "base_automation", "purchase"],
    "installable": True,
    "application": True,
    "data": [
        "data/ir_config_parameter.xml",
        "data/school_management_data.xml",
        "security/ir.model.access.csv",
        "security/school_management_record_rules.xml",
        "wizard/recheck_result_view.xml",
        "wizard/select_player_view.xml",
        "views/school_student.xml",
        "views/school_library.xml",
        "views/school_sports.xml",
        "views/school_teacher.xml",
        "views/school_result.xml",
        "views/school_main_menu.xml",
    ],
    "demo": [
        "demo/school_management_demo_data.xml",
    ],
    "license": "Other proprietary",
}
